package com.bgv.coreservice.domain;

public enum FeatureCode {
    RELATIONSHIP_BACKGROUND_CHECK,
    TENANT_VERIFICATION,
    DOMESTIC_WORKER_VERIFICATION,
    FREELANCER_VERIFICATION,
    ONLINE_SELLER_VERIFICATION,
    DATING_PROFILE_AUTHENTICITY,
    GLOBAL_IDENTITY_CHECK,
    CHAT_ANALYSIS,
    PAN_VERIFY,
    DRIVING_LICENSE_VERIFY,
    UNLIMITED
}
