import { motion } from "framer-motion";
import { FileText, Download, Shield, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import ScrollReveal from "@/components/ScrollReveal";

const SampleReport = () => {
  return (
    <section className="py-16 md:py-24 relative overflow-hidden">
      <div className="container mx-auto px-4 relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 items-center max-w-6xl mx-auto">
          <ScrollReveal>
            <div>
              <span className="inline-flex items-center gap-2 px-4 py-1.5 bg-primary/10 text-primary text-xs font-semibold rounded-full mb-4 border border-primary/20 uppercase tracking-widest">
                Sample Output
              </span>
              <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">
                AI Verification Report
              </h2>
              <p className="text-muted-foreground mb-6 leading-relaxed">
                Every verification generates a detailed report with Trust Score, risk analysis and clear action signals.
              </p>
              <div className="space-y-4 mb-8">
                {[
                  { icon: Shield, text: "Identity verification with document analysis" },
                  { icon: Clock, text: "Timeline of digital & real-world signals" },
                  { icon: FileText, text: "Fraud probability with AI reasoning" },
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3 text-sm text-muted-foreground">
                    <item.icon className="w-4 h-4 text-primary shrink-0" />
                    <span>{item.text}</span>
                  </div>
                ))}
              </div>
              <Link to="/sample-report/view">
                <Button variant="outline" className="group hover-lift">
                  <Download className="w-4 h-4 mr-2" />
                  View & Download Sample Report
                </Button>
              </Link>
            </div>
          </ScrollReveal>

          <ScrollReveal direction="scale">
            <div className="glass-card rounded-2xl p-6 relative overflow-hidden">
              <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-primary to-transparent" />
              
              {/* Mock report */}
              <div className="flex items-center gap-3 mb-6 pb-4 border-b border-border/50">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  <FileText className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <p className="font-bold text-foreground text-sm">VerifyStack AI Report</p>
                  <p className="text-xs text-muted-foreground font-mono">Report #VS-2026-00847</p>
                </div>
              </div>

              <div className="space-y-4">
                {[
                  { label: "Subject",           value: "Rahul K.",   highlight: false, redacted: true },
                  { label: "Trust Score",        value: "87 / 100",  highlight: true,  redacted: false },
                  { label: "Identity Match",     value: "Confirmed ✓", highlight: false, green: true },
                  { label: "Criminal Check",     value: "Clear ✓",   highlight: false, green: true },
                  { label: "Address Verified",   value: "Confirmed ✓", highlight: false, green: true },
                  { label: "Risk Level",         value: "Low",       highlight: false, green: true },
                  { label: "Fraud Probability",  value: "2.3%",      highlight: false, redacted: false },
                ].map((row, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    transition={{ delay: i * 0.08 }}
                    viewport={{ once: true }}
                    className="flex items-center justify-between py-2 border-b border-border/30 last:border-0"
                  >
                    <span className="text-xs text-muted-foreground font-mono uppercase tracking-wider">{row.label}</span>
                    <span className={`text-sm font-semibold ${
                      row.highlight ? "gradient-text" :
                      row.green    ? "text-green-400" :
                      row.redacted ? "text-muted-foreground italic" :
                      "text-foreground"
                    }`}>
                      {row.value}
                    </span>
                  </motion.div>
                ))}
              </div>

              <div className="mt-6 pt-4 border-t border-border/50 flex items-center justify-between">
                <span className="text-xs text-muted-foreground font-mono">Generated by AI Engine v3.2</span>
                <div className="flex items-center gap-1 text-xs text-trust">
                  <Shield className="w-3 h-3" />
                  Encrypted
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
};

export default SampleReport;
