spring.datasource.url=jdbc:postgresql://dpg-d50f7vp5pdvs739215kg-a.singapore-postgres.render.com/bgv_auth_db
spring.datasource.username=bgv_auth_db_user
spring.datasource.password=wIF3oEkjUfLI0glZ7aLZP5J1CdJEsgtq
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

billing.service.url=https://bgv-billing-service.onrender.com
ocr.service.url=https://fake-ocr-service.com
llm.analysis.service.url=https://fake-llm-analysis-service.com
notification.service.url=https://fake-notification-service.com
storage.service.url=https://fake-storage-service.com

gemini.api.key=AIzaSyBJifq2sEhQwGRdr6BjAcozBDx0Zrh_KWg
